name: Release

on:
  push: 

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Dependencies
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Make
      run: |
        make defconfig
        make download -j8
        make -j8
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          bin/targets/ipq60xx/generic/openwrt-ipq60xx-generic-cmiot_ax18-squashfs-nand-factory.ubi
          bin/targets/ipq60xx/generic/openwrt-ipq60xx-generic-cmiot_ax18-squashfs-nand-sysupgrade.bin
          bin/targets/ipq60xx/generic/sha256sums
      env:
        GITHUB_TOKEN: ${{ secrets.ENV_TOKEN }}
